### ISSUE TITLE
Problems running Vertx-Web Java API with Handlebars

### ISSUE THREAD

**Issue by fwgreen** [vert-x3/vertx-lang-ceylon#18]
I'm using Ceylon with the [plain Java API](https://github.com/fwgreen/HelloVertx) and runs without issues even as a Ceylon fatjar, but if I add`vertx-web-templ-handlebars` to my project I get a server error at run time and trying to build a Ceylon fatjar...
```
Module org.apache.commons:commons-lang3 has multiple versions loaded: 3.1, 3.4 (use "--force" to select latest version 3.4)
Module org.slf4j:slf4j-api has multiple versions loaded: 1.6.4, 1.7.21 (use "--force" to select latest version 1.7.21)
ceylon fat-jar: Module conflict error prevented classpath generation: try
running "ceylon info --print-overrides app/1.0.0" to display an override file
you can use with "ceylon classpath --overrides override.xml app/1.0.0" or try
with "ceylon classpath --force app/1.0.0" to select the latest versions
```
Forcing the latest versions ...
```
Mar 20, 2017 5:18:21 PM io.vertx.core.impl.DeploymentManager
SEVERE: org/apache/commons/lang3/ArrayUtils
java.lang.NoClassDefFoundError: org/apache/commons/lang3/ArrayUtils
        at io.vertx.ext.web.templ.impl.HandlebarsTemplateEngineImpl.<init>(HandlebarsTemplateEngineImpl.java:48)
        at io.vertx.ext.web.templ.HandlebarsTemplateEngine.create(HandlebarsTemplateEngine.java:50)
        at app.Server.start(run.ceylon:11)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:434)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.ArrayUtils
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
```

**Comment by pmlopes** [comment]
@fwgreen Can you check with 3.4.1? I've been aligning dependency versions on many modules and it could be fixed already. Otherwise can you troubleshoot where the conflicting versions come from?

**Comment by fwgreen** [comment]
I'm having the same problem with 3.4.1.  With 3.3.3 the conflict is only with `slf4j-api` and forcing the newer version allows the jar to run.  I'll try to find the source of the conflict with `commons-lang3`.
